//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace sb4.Models
{
    public partial class Comment
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int PostId
        {
            get { return _postId; }
            set
            {
                if (_postId != value)
                {
                    if (Post != null && Post.Id != value)
                    {
                        Post = null;
                    }
                    _postId = value;
                }
            }
        }
        private int _postId;
    
        public virtual string Author
        {
            get;
            set;
        }
    
        public virtual string Content
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }
    
        public virtual bool IsApproved
        {
            get;
            set;
        }
    
        public virtual bool ShouldEmailNotifications
        {
            get;
            set;
        }
    
        public virtual string Email
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Post Post
        {
            get { return _post; }
            set
            {
                if (!ReferenceEquals(_post, value))
                {
                    var previousValue = _post;
                    _post = value;
                    FixupPost(previousValue);
                }
            }
        }
        private Post _post;

        #endregion
        #region Association Fixup
    
        private void FixupPost(Post previousValue)
        {
            if (previousValue != null && previousValue.Comments.Contains(this))
            {
                previousValue.Comments.Remove(this);
            }
    
            if (Post != null)
            {
                if (!Post.Comments.Contains(this))
                {
                    Post.Comments.Add(this);
                }
                if (PostId != Post.Id)
                {
                    PostId = Post.Id;
                }
            }
        }

        #endregion
    }
}
