//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace sb4.Models
{
    public partial class OutputItem
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SiteId
        {
            get { return _siteId; }
            set
            {
                if (_siteId != value)
                {
                    if (Site != null && Site.Id != value)
                    {
                        Site = null;
                    }
                    _siteId = value;
                }
            }
        }
        private int _siteId;
    
        public virtual int CategoryId
        {
            get { return _categoryId; }
            set
            {
                if (_categoryId != value)
                {
                    if (OutputCategory != null && OutputCategory.Id != value)
                    {
                        OutputCategory = null;
                    }
                    _categoryId = value;
                }
            }
        }
        private int _categoryId;
    
        public virtual string Title
        {
            get;
            set;
        }
    
        public virtual string Link
        {
            get;
            set;
        }
    
        public virtual string ISBN
        {
            get;
            set;
        }
    
        public virtual string Authors
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> Date
        {
            get;
            set;
        }
    
        public virtual string Publisher
        {
            get;
            set;
        }
    
        public virtual string Notes
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual OutputCategory OutputCategory
        {
            get { return _outputCategory; }
            set
            {
                if (!ReferenceEquals(_outputCategory, value))
                {
                    var previousValue = _outputCategory;
                    _outputCategory = value;
                    FixupOutputCategory(previousValue);
                }
            }
        }
        private OutputCategory _outputCategory;
    
        public virtual Site Site
        {
            get { return _site; }
            set
            {
                if (!ReferenceEquals(_site, value))
                {
                    var previousValue = _site;
                    _site = value;
                    FixupSite(previousValue);
                }
            }
        }
        private Site _site;

        #endregion
        #region Association Fixup
    
        private void FixupOutputCategory(OutputCategory previousValue)
        {
            if (previousValue != null && previousValue.OutputItems.Contains(this))
            {
                previousValue.OutputItems.Remove(this);
            }
    
            if (OutputCategory != null)
            {
                if (!OutputCategory.OutputItems.Contains(this))
                {
                    OutputCategory.OutputItems.Add(this);
                }
                if (CategoryId != OutputCategory.Id)
                {
                    CategoryId = OutputCategory.Id;
                }
            }
        }
    
        private void FixupSite(Site previousValue)
        {
            if (previousValue != null && previousValue.OutputItems.Contains(this))
            {
                previousValue.OutputItems.Remove(this);
            }
    
            if (Site != null)
            {
                if (!Site.OutputItems.Contains(this))
                {
                    Site.OutputItems.Add(this);
                }
                if (SiteId != Site.Id)
                {
                    SiteId = Site.Id;
                }
            }
        }

        #endregion
    }
}
