//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace sb4.Models
{
    public partial class PostCategory
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual int SiteId
        {
            get { return _siteId; }
            set
            {
                if (_siteId != value)
                {
                    if (Site != null && Site.Id != value)
                    {
                        Site = null;
                    }
                    _siteId = value;
                }
            }
        }
        private int _siteId;
    
        public virtual string Name
        {
            get;
            set;
        }
    
        public virtual string DisplayName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Site Site
        {
            get { return _site; }
            set
            {
                if (!ReferenceEquals(_site, value))
                {
                    var previousValue = _site;
                    _site = value;
                    FixupSite(previousValue);
                }
            }
        }
        private Site _site;

        #endregion
        #region Association Fixup
    
        private void FixupSite(Site previousValue)
        {
            if (previousValue != null && previousValue.PostCategories.Contains(this))
            {
                previousValue.PostCategories.Remove(this);
            }
    
            if (Site != null)
            {
                if (!Site.PostCategories.Contains(this))
                {
                    Site.PostCategories.Add(this);
                }
                if (SiteId != Site.Id)
                {
                    SiteId = Site.Id;
                }
            }
        }

        #endregion
    }
}
