//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace sb4.Models
{
    public partial class sellsbrothersEntities : ObjectContext
    {
        public const string ConnectionString = "name=sellsbrothersEntities";
        public const string ContainerName = "sellsbrothersEntities";
    
        #region Constructors
    
        public sellsbrothersEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public sellsbrothersEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public sellsbrothersEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Comment> Comments
        {
            get { return _comments  ?? (_comments = CreateObjectSet<Comment>("Comments")); }
        }
        private ObjectSet<Comment> _comments;
    
        public ObjectSet<Post> Posts
        {
            get { return _posts  ?? (_posts = CreateObjectSet<Post>("Posts")); }
        }
        private ObjectSet<Post> _posts;
    
        public ObjectSet<TinyLink> TinyLinks
        {
            get { return _tinyLinks  ?? (_tinyLinks = CreateObjectSet<TinyLink>("TinyLinks")); }
        }
        private ObjectSet<TinyLink> _tinyLinks;
    
        public ObjectSet<Badge> Badges
        {
            get { return _badges  ?? (_badges = CreateObjectSet<Badge>("Badges")); }
        }
        private ObjectSet<Badge> _badges;
    
        public ObjectSet<LandingZone> LandingZones
        {
            get { return _landingZones  ?? (_landingZones = CreateObjectSet<LandingZone>("LandingZones")); }
        }
        private ObjectSet<LandingZone> _landingZones;
    
        public ObjectSet<OutputCategory> OutputCategories
        {
            get { return _outputCategories  ?? (_outputCategories = CreateObjectSet<OutputCategory>("OutputCategories")); }
        }
        private ObjectSet<OutputCategory> _outputCategories;
    
        public ObjectSet<OutputItem> OutputItems
        {
            get { return _outputItems  ?? (_outputItems = CreateObjectSet<OutputItem>("OutputItems")); }
        }
        private ObjectSet<OutputItem> _outputItems;
    
        public ObjectSet<PostCategory> PostCategories
        {
            get { return _postCategories  ?? (_postCategories = CreateObjectSet<PostCategory>("PostCategories")); }
        }
        private ObjectSet<PostCategory> _postCategories;
    
        public ObjectSet<Site> Sites
        {
            get { return _sites  ?? (_sites = CreateObjectSet<Site>("Sites")); }
        }
        private ObjectSet<Site> _sites;
    
        public ObjectSet<Ad> Ads
        {
            get { return _ads  ?? (_ads = CreateObjectSet<Ad>("Ads")); }
        }
        private ObjectSet<Ad> _ads;

        #endregion
    }
}
